# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=tree" ];
    };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/42f84f76-d5d8-412e-9586-957c1be7bcc1";

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/state" =
    { device = "/dev/disk/by-uuid/9f0f676d-83cd-4dd9-ac7d-247ee8fb9c0b";
      fsType = "btrfs";
      options = [ "subvol=state" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A4FA-14F9";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
